apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  labels:
    app: myapp
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: httpd-app
        image: quay.io/soumya7410/httpd-app:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: content
          mountPath: /var/www/html/index.html
          subPath: index.html
      volumes:
      - name: content
        configMap:
          name: app-blue-content
